[package]
name = "game_server_logic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { workspace = true }
hexx = { version = "0.17", features = ["serde"] }
bevy_ggrs = { workspace = true }